---
title: "Starting with data"
output: html_notebook
---
# DATAFRAMES

## Download data
```{r}
download.file("https://ndownloader.figshare.com/files/2292169",
              "data/portal_data_joined.csv")
```
```{r}
surveys <- read.csv("data/portal_data_joined.csv")
```


```{r}
head(surveys, 10)
```

```{r}
surveys
```
```{r}
tail(surveys)
```

```{r}
str(surveys)
```

```{r}
dim(surveys)
nrow(surveys)
ncol(surveys)
```

```{r}
names(surveys)
```

```{r}
rownames(surveys)
```

```{r}
summary(surveys)
```
```{r}
plot(surveys$sex)
```
# Subsetting dataframes
```{r}
surveys[1]
dim(surveys[1])
```
```{r}
surveys[,1, drop = F]
```

```{r}
surveys[,1]
```
```{r}
surveys[1,1]
```

```{r}
surveys[1:3, 1]
```

```{r}
surveys[c(2,4), 1]
```
```{r}
surveys["species_id"]
```
```{r}
surveys[,"species_id"]
```
```{r}
surveys[["species_id"]]
```

```{r}
surveys$record_i
```

# factors

```{r}
sex <- factor(c("male", "female", "male", "female"))
sex
```

```{r}
plot(sex)
```


```{r}
levels(sex)
```

```{r}
nlevels(sex)
```
```{r}
sex <- factor(sex, levels = c("male", "female"))
sex
```
```{r}
plot(sex)
```
```{r}
f <- factor(c(1990, 1983, 1977, 1998, 1990))
f
```

```{r}
as.numeric(f)
```

```{r}
as.numeric(as.character(f))
```

